# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.7
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: arthurrabelopro@gmail.com
author_name: p2arthur
contract_name: source_factory
preset_name: production
project_name: WeSource-contracts

